### ISSUE TITLE
SwiftUIとUIImagePickerを組み合わせるサンプルアプリについて

### ISSUE THREAD

**Issue by yosuke1985** [SatoTakeshiX/SwiftUICatalog#10]
勉強になってます、ありがとうございます。
README.MDに記載されている
> 追加アプリ
> 「1人でアプリを作る人を支えるSwiftUI開発レシピ」には掲載していませんが、SwiftUIとUIImagePickerを組み合わせるサンプルアプリもあります。
> 
> サンプルアプリ

って、探してもないのですが、どこにありますでしょうか？！

**Comment by yosuke1985** [comment]
@SatoTakeshiX

**Comment by SatoTakeshiX** [comment]
連絡遅れました。
@yosuke1985 san

> 追加アプリ
「1人でアプリを作る人を支えるSwiftUI開発レシピ」には掲載していませんが、SwiftUIとUIImagePickerを組み合わせるサンプルアプリもあります。


https://github.com/SatoTakeshiX/SwiftUICatalog/tree/master/FilterSample

はこちらです。
UIImagePickerから画像を出し、画像をフィルターするアプリになります。どうぞこちらをためしてください。
READMEにも追加します。

**Comment by yosuke1985** [comment]
連絡おくれました、ご返信ありがとうございます！拝見しました！とても勉強になりました！ありがとうございます！
