### ISSUE TITLE
GitHubApiClientSampleのHomeViewModelTestsのtestOnEnterのテストが通らない件について

### ISSUE THREAD

**Issue by yosuke1985** [SatoTakeshiX/SwiftUICatalog#12]
testOnEnterのテストが通らない件についてアドバイスお願いしたいのですが、
cardViewInputsに値が流れてきていないのでしょうか？

**Comment by SatoTakeshiX** [comment]
報告ありがとうございます。
確かにテストが通らないですね。みてみます。

**Comment by SatoTakeshiX** [comment]
HomeViewModelの`convertInput`メソッドでnilを返していました。
ここ画像データが作成できない場合CardView.Input作成されないのでTest失敗していたようです。
画像がなくてもCardView.Inputはつくられて良い気がするので`convertInput`の方直します

**Comment by SatoTakeshiX** [comment]
@yosuke1985 マージしました。ご確認いただければと思います

**Comment by yosuke1985** [comment]
なるほど、そうでしたか、ありがとうございます！めちゃめちゃ勉強になります！！

**Comment by SatoTakeshiX** [comment]
よかったです！issueを閉じますね！
